# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-bf8aaa09-c450-47df-96d5-ac39590b7e1f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-bf8aaa09-c450-47df-96d5-ac39590b7e1f".device = "/dev/disk/by-uuid/bf8aaa09-c450-47df-96d5-ac39590b7e1f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DC3E-5D97";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-26f0579d-79fe-4ff9-96fa-f432718e7385"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
